# Generated by Django 3.0.5 on 2020-04-15 15:18

# Generated by Django 3.0.5 on 2020-04-15 15:18

from django.db import migrations


def load_data(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Warehouse = apps.get_model("amazonApp", "Warehouse")
    Warehouse.objects.using(db_alias).bulk_create([
        Warehouse(wh_x=50, wh_y=40),
        Warehouse(wh_x=50, wh_y=60)

    ])
    AmazonProduct = apps.get_model("amazonApp", "AmazonProduct")
    AmazonProduct.objects.using(db_alias).bulk_create([
        AmazonProduct(product_name="apple", product_desc="apple"),
        AmazonProduct(product_name="banana", product_desc="banana"),
        AmazonProduct(product_name="iphone", product_desc="probably overpriced"),
        AmazonProduct(product_name="iphone7", product_desc="extremely overpriced")

    ])


class Migration(migrations.Migration):
    dependencies = [
        ('amazonApp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]