# Generated by Django 3.0.5 on 2020-04-15 15:18

from django.db import migrations

def load_data(apps,schema_editor):
    
    db_alias = schema_editor.connection.alias
    Warehouse = apps.get_model("amazonApp", "Warehouse")
    Warehouse.objects.using(db_alias).bulk_create([
        Warehouse(id=1,wh_name='s',wh_x=1, wh_y=100)
    ])
    wh=Warehouse.objects.get(pk=1)
    AmazonProduct = apps.get_model("amazonApp", "AmazonProduct")
    AmazonProduct.objects.using(db_alias).bulk_create([
        AmazonProduct(warehouse_id=wh,product_name="apple", product_quantity=1, product_desc="apple"),
        AmazonProduct(warehouse_id=wh,product_name = "banana", product_quantity=2, product_desc="banana")
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('amazonApp', '0001_initial'),
    ]

    operations = [
            migrations.RunPython(load_data)
    ]
