FROM postgres 
ENV POSTGRES_PASSWORD password 
ENV PGPASSWORD password
ENV POSTGRES_DB amazondb
#COPY init.sql /docker-entrypoint-initdb.d/
#RUN psql amazondb postgres -a -h localhost -p 5433 -f clear_tables.sql
#COPY *.csv /docker-entrypoint-intdb.d/
